### ISSUE TITLE
No example input file provided - Unable to run task with Bulk command

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-mongodb#3]
### Expected Behavior

Successfully running the example given here: https://kestra.io/plugins/tasks/io.kestra.plugin.mongodb.Bulk

### Actual Behaviour

The flow example of type: "io.kestra.plugin.mongodb.Bulk"mentioned in this [page](https://kestra.io/plugins/tasks/io.kestra.plugin.mongodb.Bulk) uses an input file in this line: `from: "{{ inputs.file }}"`

But it is not clear exactly what this file should contain. It is unclear as to how to represent the operations and the command in this file. Without this information, I am unable to run this exanmple.

Note: The other MongoDB commands where input file is required is a json file containing the documents. But this one is a special case as we also need to put in the operation details along with the document.

### Steps To Reproduce

Trying to run the flow example:

```yaml
id: "bulk"
type: "io.kestra.plugin.mongodb.Bulk"
connection:
  uri: "mongodb://root:example@localhost:27017/?authSource=admin"
database: "my_database"
collection: "my_collection"
from: "{{ inputs.file }}"
```

### Environment Information

- Kestra Version: 0.14.0
- Plugin version: 0.14.0
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker): N/A

### Example flow

```yaml
id: "bulk"
type: "io.kestra.plugin.mongodb.Bulk"
connection:
  uri: "mongodb://root:example@localhost:27017/?authSource=admin"
database: "my_database"
collection: "my_collection"
from: "{{ inputs.file }}"
```
